//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarSet
    {
        public int ID { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public Nullable<double> Price { get; set; }
        public string GN { get; set; }
        public Nullable<double> Year { get; set; }
    }
}
